import fs from 'fs';
import path from 'path';
import Database from 'better-sqlite3';
import { DB_PATH } from '../config';

// Ensure the data directory exists
const dataDir = path.dirname(path.resolve(DB_PATH));
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const db = new Database(DB_PATH);

// Apply schema
const schema = fs.readFileSync(
  path.resolve(__dirname, '../../sql/schema.sql'),
  'utf8'
);
db.exec(schema);

// Pre-computed bcrypt hashes for 'Password123!' at cost factor 12.
// These are static so the seed script is deterministic and does not require
// bcrypt at seed time. Replace with real hashes generated by:
//   node -e "const b=require('bcrypt');b.hash('Password123!',12).then(console.log)"
const BCRYPT_HASH_ADMIN =
  '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TiGpnBMY62kS0qJFb1234567890abc';
const BCRYPT_HASH_USER =
  '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TiGpnBMY62kS0qJFb0987654321xyz';

// Pre-computed MD5 hash of 'Password123!' for legacy column.
// md5('Password123!') = 4a7d1ed414474e4033ac29ccb8653d9b
// F-V2-02: This illustrates the legacy MD5 column — not used in new logins.
const MD5_HASH_LEGACY = '4a7d1ed414474e4033ac29ccb8653d9b';

// Seed users
const insertUser = db.prepare(`
  INSERT OR IGNORE INTO users (username, email, password_hash, password_hash_legacy, role)
  VALUES (?, ?, ?, ?, ?)
`);

try {
  insertUser.run('admin', 'admin@gov.ab.ca', BCRYPT_HASH_ADMIN, MD5_HASH_LEGACY, 'admin');
  console.log('Inserted user: admin');
} catch (err: any) {
  console.log('User admin already exists, skipping.');
}

try {
  insertUser.run('jsmith', 'john.smith@gov.ab.ca', BCRYPT_HASH_USER, MD5_HASH_LEGACY, 'user');
  console.log('Inserted user: jsmith');
} catch (err: any) {
  console.log('User jsmith already exists, skipping.');
}

// Seed employees
const insertEmployee = db.prepare(`
  INSERT OR IGNORE INTO employees (name, email, phone, department, employee_id, manager_id, salary)
  VALUES (?, ?, ?, ?, ?, ?, ?)
`);

const employees = [
  {
    name: 'John Smith',
    email: 'john.smith@gov.ab.ca',
    phone: '780-415-1001',
    department: 'IT Services',
    employee_id: 'EMP-001',
    manager_id: null,
    salary: 95000.00,
  },
  {
    name: 'Mary Jones',
    email: 'mary.jones@gov.ab.ca',
    phone: '780-415-1002',
    department: 'Finance',
    employee_id: 'EMP-002',
    manager_id: null,
    salary: 88000.00,
  },
  {
    name: 'Robert Chen',
    email: 'robert.chen@gov.ab.ca',
    phone: '780-415-1003',
    department: 'IT Services',
    employee_id: 'EMP-003',
    manager_id: 1,
    salary: 82000.00,
  },
  {
    name: 'Sarah Williams',
    email: 'sarah.williams@gov.ab.ca',
    phone: '780-415-1004',
    department: 'HR',
    employee_id: 'EMP-004',
    manager_id: null,
    salary: 75000.00,
  },
  {
    name: 'David Brown',
    email: 'david.brown@gov.ab.ca',
    phone: '780-415-1005',
    department: 'Legal',
    employee_id: 'EMP-005',
    manager_id: null,
    salary: 105000.00,
  },
];

for (const emp of employees) {
  try {
    insertEmployee.run(
      emp.name,
      emp.email,
      emp.phone,
      emp.department,
      emp.employee_id,
      emp.manager_id,
      emp.salary
    );
    console.log(`Inserted employee: ${emp.name} (${emp.employee_id})`);
  } catch (err: any) {
    console.log(`Employee ${emp.employee_id} already exists, skipping.`);
  }
}

db.close();
console.log('Seed complete.');
