#!/usr/bin/env node
/**
 * build-readme.mjs — fill autogen markers in README.md so they stay in
 * lock-step with the codebase. Idempotent: running twice produces the
 * same output as running once.
 *
 * Markers (placed in your README anywhere you want the live value):
 *   <!-- AUTOGENERATED:migrations-count -->NN<!-- /AUTOGENERATED:migrations-count -->
 *   <!-- AUTOGENERATED:openapi-version -->X.Y.Z<!-- /AUTOGENERATED:openapi-version -->
 *
 * Auto-discovers README, openapi.yaml, and migrations dir. Drop a
 * .docs-sync.json in the project root to override paths if needed.
 *
 * Usage:
 *   node build-readme.mjs              # run from project root
 *   node build-readme.mjs --root <dir> # run against a specific project
 */

import fs from 'node:fs';
import path from 'node:path';

const argv = process.argv.slice(2);
let ROOT = process.cwd();
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--root') ROOT = path.resolve(argv[++i]);
}
function findRoot(start) {
  let cur = path.resolve(start);
  for (let i = 0; i < 12; i++) {
    if (fs.existsSync(path.join(cur, 'package.json')) ||
        fs.existsSync(path.join(cur, '.git'))) return cur;
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return path.resolve(start);
}
ROOT = findRoot(ROOT);

const cfgPath = path.join(ROOT, '.docs-sync.json');
let CFG = {};
if (fs.existsSync(cfgPath)) {
  try { CFG = JSON.parse(fs.readFileSync(cfgPath, 'utf8')); } catch {}
}
function firstExisting(rels) {
  for (const r of rels) {
    const abs = path.join(ROOT, r);
    if (fs.existsSync(abs)) return abs;
  }
  return null;
}
const README = CFG.readme ? path.join(ROOT, CFG.readme)
  : firstExisting(['README.md', 'README.MD', 'app/README.md', 'docs/README.md']);
const OPENAPI = CFG.openapi ? path.join(ROOT, CFG.openapi)
  : firstExisting(['openapi.yaml', 'openapi.yml', 'server/openapi.yaml',
                   'api/openapi.yaml', 'docs/openapi.yaml', 'swagger.yaml']);
function findMigrations() {
  if (CFG.migrations?.dir) return path.join(ROOT, CFG.migrations.dir);
  for (const rel of ['server/migrations', 'migrations', 'db/migrations', 'db/migrate']) {
    const abs = path.join(ROOT, rel);
    if (fs.existsSync(abs) && fs.statSync(abs).isDirectory()) return abs;
  }
  return null;
}
const MIGRATIONS = findMigrations();
const MIG_PATTERN = new RegExp(CFG.migrations?.pattern || '^\\d{3}_.*\\.sql$');

if (!README) {
  console.error('build-readme: no README.md found at the project root.');
  process.exit(1);
}

let text = fs.readFileSync(README, 'utf8');
const replacements = [];

if (MIGRATIONS) {
  const count = fs.readdirSync(MIGRATIONS).filter(f => MIG_PATTERN.test(f)).length;
  text = replaceMarker(text, 'migrations-count', String(count), replacements);
}
if (OPENAPI) {
  const oapi = fs.readFileSync(OPENAPI, 'utf8');
  const m = oapi.match(/^\s*version:\s*['"]?(\d+\.\d+\.\d+)/m);
  if (m) text = replaceMarker(text, 'openapi-version', m[1], replacements);
}

if (replacements.length === 0) {
  console.log('build-readme: no markers found in README.md.');
  console.log('Add markers like:');
  console.log('  <!-- AUTOGENERATED:migrations-count -->63<!-- /AUTOGENERATED:migrations-count -->');
  console.log('  <!-- AUTOGENERATED:openapi-version -->1.0.0<!-- /AUTOGENERATED:openapi-version -->');
  process.exit(0);
}

fs.writeFileSync(README, text);
console.log(`build-readme: updated ${replacements.length} marker section(s):`);
for (const r of replacements) {
  console.log(`  ${r.name} -> ${r.value}${r.changed ? ' (CHANGED)' : ' (unchanged)'}`);
}

function replaceMarker(text, name, newValue, replacements) {
  const re = new RegExp(
    `<!--\\s*AUTOGENERATED:${name}\\s*-->([\\s\\S]*?)<!--\\s*/AUTOGENERATED:${name}\\s*-->`,
    'g',
  );
  let found = false;
  const replaced = text.replace(re, (_, currentValue) => {
    found = true;
    const changed = currentValue.trim() !== newValue.trim();
    replacements.push({ name, value: newValue, changed });
    return `<!-- AUTOGENERATED:${name} -->${newValue}<!-- /AUTOGENERATED:${name} -->`;
  });
  if (!found) console.warn(`build-readme: marker '${name}' not present in README — skipped.`);
  return replaced;
}
