/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    LoadingSkeleton: typeof import('./src/components/common/LoadingSkeleton.vue')['default']
    MapView: typeof import('./src/components/explore/MapView.vue')['default']
    PwaInstallPrompt: typeof import('./src/components/pwa/PwaInstallPrompt.vue')['default']
    PwaUpdatePrompt: typeof import('./src/components/pwa/PwaUpdatePrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmissionDetailView: typeof import('./src/components/submissions/SubmissionDetailView.vue')['default']
    ThemeSwitcher: typeof import('./src/components/layout/ThemeSwitcher.vue')['default']
  }
}
