#!/usr/bin/env node
// WAF detection. Dispatch: wafw00f (richest) → Node heuristic probe (3 requests + header/body sigs).
// Native fallback identifies Cloudflare, Akamai, AWS WAF, Azure, Sucuri, Incapsula, etc.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { whichBin, runBin, requireArg, httpFetch } from "./_runner.js";

function tryBinary(url) {
  if (!whichBin("wafw00f")) return null;
  const jsonPath = path.join(os.tmpdir(), `wafw00f_${Date.now()}_${process.pid}.json`);
  try {
    const res = runBin("wafw00f", [url, "-o", jsonPath, "-f", "json"], { timeout: 60000 });
    if (res.killed) return { error: "wafw00f timed out", target: url };
    if (fs.existsSync(jsonPath) && fs.statSync(jsonPath).size > 0) {
      const data = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
      if (Array.isArray(data) && data.length > 0) {
        const e = data[0];
        const name = e.firewall || "";
        const detected = !!(name && name.toLowerCase() !== "none");
        return {
          target: url,
          source: "wafw00f",
          waf_detected: detected,
          waf_name: detected ? name : "",
          detection_method: e.manufacturer || "",
          bypass_notes: "",
        };
      }
    }
    const text = (res.stdout || "") + (res.stderr || "");
    if (/is behind/i.test(text)) {
      const lines = text.split(/\r?\n/).filter((l) => /is behind/i.test(l));
      const name = lines.length ? lines[0].split(/is behind/i).pop().trim().replace(/\.$/, "") : "Unknown";
      return { target: url, source: "wafw00f", waf_detected: true, waf_name: name, detection_method: "text_parsing", bypass_notes: "" };
    }
    return null;
  } finally {
    try { fs.unlinkSync(jsonPath); } catch { /* ignore */ }
  }
}

// (regex match against headers/body, name, method)
const HEADER_SIGS = [
  { re: /cf-ray|__cf_bm|cf-cache-status/i, name: "Cloudflare", source: "header" },
  { re: /x-sucuri-id|x-sucuri-cache/i, name: "Sucuri CloudProxy", source: "header" },
  { re: /^x-akamai-/i, name: "Akamai", source: "header" },
  { re: /akamai-grn|akamaighost/i, name: "Akamai", source: "header" },
  { re: /^x-amz-cf-id|x-amz-cf-pop/i, name: "AWS CloudFront", source: "header" },
  { re: /^x-amzn-(requestid|errortype|trace)/i, name: "AWS WAF", source: "header" },
  { re: /^x-azure-ref|x-msedge-ref/i, name: "Azure Front Door / Edge", source: "header" },
  { re: /^x-iinfo|incap_ses|visid_incap/i, name: "Imperva Incapsula", source: "header" },
  { re: /^x-fw-(serve|hash|debug)/i, name: "Imperva", source: "header" },
  { re: /server:\s*BigIP|F5-?TrafficShield/i, name: "F5 BIG-IP", source: "header" },
  { re: /server:\s*FortiWeb|FORTIWAFSID/i, name: "Fortinet FortiWeb", source: "header" },
  { re: /barracuda/i, name: "Barracuda WAF", source: "header" },
  { re: /citrix.*netscaler|ns_af=|nscopt/i, name: "Citrix NetScaler / ADC", source: "header" },
  { re: /mod_security|NOYB/i, name: "ModSecurity", source: "header" },
];

const BODY_SIGS = [
  { re: /Cloudflare Ray ID|cdn-cgi\/error\//i, name: "Cloudflare" },
  { re: /Access Denied[\s\S]{0,200}reference #\d+\.[0-9a-f]+/i, name: "Akamai" },
  { re: /Request blocked\.[\s\S]{0,200}AWS WAF/i, name: "AWS WAF" },
  { re: /<title>403 Forbidden<\/title>[\s\S]{0,200}sucuri/i, name: "Sucuri CloudProxy" },
  { re: /Incapsula incident ID|_Incapsula_Resource/i, name: "Imperva Incapsula" },
  { re: /ModSecurity[\s\S]{0,50}reference/i, name: "ModSecurity" },
  { re: /Generated by Wordfence/i, name: "Wordfence" },
  { re: /the request you made[\s\S]{0,200}edgesuite/i, name: "Akamai EdgeSuite" },
];

function matchSigs(headersObj, body) {
  const flatHeaders = Object.entries(headersObj || {})
    .map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(",") : v}`)
    .join("\n");
  for (const sig of HEADER_SIGS) {
    if (sig.re.test(flatHeaders)) return { name: sig.name, source: sig.source };
  }
  if (body) {
    for (const sig of BODY_SIGS) {
      if (sig.re.test(body)) return { name: sig.name, source: "body" };
    }
  }
  return null;
}

async function tryNative(url) {
  if (!url.startsWith("http://") && !url.startsWith("https://")) url = `http://${url}`;
  // 3 probes: clean, XSS, ShellShock-style UA
  const probes = [
    { label: "clean", target: url, headers: {} },
    {
      label: "xss",
      target: url + (url.includes("?") ? "&" : "?") + "x=" + encodeURIComponent("<script>alert(1)</script>"),
      headers: {},
    },
    {
      label: "shellshock_ua",
      target: url,
      headers: { "User-Agent": "() { :; }; echo; /bin/cat /etc/passwd" },
    },
  ];

  const results = [];
  for (const p of probes) {
    const r = await httpFetch(p.target, { headers: p.headers, timeout: 12000 });
    results.push({ label: p.label, status: r.status, headers: r.headers || {}, body: (r.body || "").slice(0, 4000), error: r.error });
  }

  // Signature match across all probes
  for (const r of results) {
    if (!r.headers) continue;
    const m = matchSigs(r.headers, r.body);
    if (m) {
      return {
        target: url,
        source: "node:heuristic",
        waf_detected: true,
        waf_name: m.name,
        detection_method: `${m.source}-signature on ${r.label} probe`,
        bypass_notes: "",
        probe_status_codes: results.map((x) => ({ label: x.label, status: x.status })),
      };
    }
  }

  // Behavioral hint: XSS or shellshock probe returns 403/406/501 while clean returns 200
  const clean = results[0];
  for (const r of results.slice(1)) {
    if (clean && clean.status && [200, 301, 302].includes(clean.status) &&
        [401, 403, 406, 419, 444, 501, 503].includes(r.status)) {
      return {
        target: url,
        source: "node:heuristic",
        waf_detected: true,
        waf_name: "Unknown",
        detection_method: `behavioral: clean=${clean.status}, ${r.label}=${r.status}`,
        bypass_notes: "Try header obfuscation, encoded payloads, or HTTP/2 smuggling",
        probe_status_codes: results.map((x) => ({ label: x.label, status: x.status })),
      };
    }
  }

  return {
    target: url,
    source: "node:heuristic",
    waf_detected: false,
    waf_name: "",
    detection_method: "no header or body signature matched",
    bypass_notes: "",
    probe_status_codes: results.map((x) => ({ label: x.label, status: x.status })),
  };
}

async function detect(url) {
  const fromBin = tryBinary(url);
  if (fromBin) return fromBin;
  return await tryNative(url);
}

const url = requireArg(process.argv, "waf_detect.js", "<url>");
detect(url)
  .then((r) => { console.log(JSON.stringify(r, null, 2)); })
  .catch((e) => {
    console.log(JSON.stringify({ error: e.message, target: url }, null, 2));
    process.exit(2);
  });
